version: '3'

services:
  # Serviço para a aplicação backend (Spring Boot com Java 21)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_app
    ports:
      - "8080:8080"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
